services:
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    user: "0"
    ports:
      - 8181:8181
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - ./influxdb3_core:/var/lib/influxdb3
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Authorization: Bearer $$INFLUXDB_TOKEN' http://localhost:8181/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  explorer:
    image: influxdata/influxdb3-ui:1.4.0
    container_name: influxdb3-explorer
    pull_policy: always
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    volumes:
      - ./influxdb3_explorer/db:/db:rw
      - ./influxdb3_explorer/config:/app-root/config:ro
    environment:
      - SESSION_SECRET_KEY=${DB_SESSION_KEY}
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: "0"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb3-core
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_PLUGINS_PREINSTALL=ae3e-plotly-panel
      - INFLUXDB_DOCKER_URL=http://influxdb3-core:8181
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_DB_NAME=${INFLUXDB_DB_NAME}
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
